name: demo.yml
# This is a demo GH Actions workflow file
on:
  pull_request: # Triggered when a pull request is opened, synchronize, or reopened
    branches: # Also can be written as ["main", "master"]
      - main

    schedule: # Define the time to run the workflow
      - cron: '0 6 * * 1-5' # Run at 6:00 UTC every weekday
      # * -> minute * -> hour * -> day of month * -> month * -> day of week

  workflow_call: # Triggered when a workflow is called
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'OverNuke'
        required: true
        type: string

  permissions:
    actions: read|write|none
    # This part can be super detailed...
    # For example, you can specify the permissions for each action
    #   checks: read|write|none
    #   contents: read|write|none
    #   deployments: read|write|none and so on...

jobs: # Now what is going to do our workflow

  build:
    runs-on: ubuntu-latest # The server to use

    steps:
      # This will set up a Node.js environment
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
